lexik_jwt_authentication:
    user_identity_field: 'storeName'
    user_id_claim: 'username'
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
