#controllers:
#    resource: ../src/Controller/
#    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

api_login_check:
    path: /api/login_check
    methods: ['POST']

api_admin_login:
    path: /api/admin_login
    methods: ['POST']
